select * from customer 

--what is the total revenue generated by male and female customers?
select gender, sum(purchase_amount) as revenue
from customer
group by gender

--which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--which are the top 5 products with the highest average review rating?
select item_purchased, round(avg (review_rating::numeric),2)
from customer
group by item_purchased 
order by avg(review_rating) desc
limit 5;

--compare the average purchase amounts between standard and express shipping
select shipping_type,
round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--do subscribed customers spend more compare average spend and total revenue between subscribers and non subscribers
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(100*sum(case when discount_applied ='Yes' Then 1 else 0 end)/count(*) ,2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status

--what is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;